## docker-compose.server.yml
services:
  webapp:
    image: ${WEBAPP_IMAGE}
    ports:
      - "8080:3000"
    env_file:
      - .env
    restart: always
  api:
    image: ${API_IMAGE}
    ports:
      - "5000:3001"
    env_file:
      - .env
    restart: always
