services:
  webapp:
    build:
      context: ./webapp
    ports:
      - "3000:3000"
    volumes:
      - "./webapp:/opt/app"
    restart: always
  api:
    build:
      context: ./api
    ports:
      - "3001:3001"
    volumes:
      - "./api:/opt/app"
    restart: always
